pygments: true
relative_permalinks: false
source: docs
dox_source: lib
dox_template: docs/api/template.ejs
destination: _site

# package.json used to build docs
package_json: 'package.json'

# explicitly order documents
table_of_contents: 
  - getting started:
    - index
  - guides:
    - index
  - examples:
    - index
  - api:
    - index
  - tools:
    - index
  
# category labels
getting_started_lbl: Getting Started
guides_lbl: Guides
examples_lbl: Examples
api_lbl: API
tools_lbl: Tools